version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
    command: python -m unittest backend/test_rag_system.py -v 